### ISSUE TITLE
German i18n need some improvements

### ISSUE THREAD

**Issue by Strean1337** [madou/armory-react#101]
Hey dude, 

i really love gw2armory but the german translations are horrible

i forked the repo and fixed the translations.

I think i will work next on the missing i18n and will add them.

I created a pull request.

**Comment by madou** [comment]
Hey! Awesome man, I was actually trying to find someone who could properly translate to german (instead of google) - was waiting for a friend of a friend haha.

So this is great, thanks for going to the effort!
