### ISSUE TITLE
Restructure root level pages (user, guild, character) to be more user friendly

### ISSUE THREAD

**Issue by madou** [madou/armory-react#112]
Currently there is a lot of white space, and users need to scroll a LOT to find the info they're interested in. And the current page setup won't scale when more information is added to the pages. Having to scroll 4+ viewports = BAD

Currently working with @ronnygit  on what would work best.

[Current design work in progress](https://lh3.googleusercontent.com/-FJ23yNStuz0/WCGlKp7S-1I/AAAAAAACkJ0/guiIL0CClNosC7wxrgXkEu0D_p2gObacACL0B/h1080/2016-11-08.png)

Would be good to take hints from other sites too, such as:
http://masteroverwatch.com/profile/pc/us/RedMage-6477

**Comment by ronnygit** [comment]
heeeeeeeeeey
