### ISSUE TITLE
Extend guild logs to show names instead of ids

### ISSUE THREAD

**Issue by madou** [madou/armory-react#143]

**Comment by Darqam** [comment]
Are you looking for a simple txt file for this? I have (as an example) one here: http://mymeanderingmind.com/GW2W_Easy_Mode/en/items/reference.txt which is continuously updated. I'm not saying you need to take this one, but would something to that effect be sufficient?

**Comment by madou** [comment]
Hey mate !

So I don't really want to use a manually updated document - would rather source everything through the api.

I already have a actions/reducers setup for items, example usage here: https://github.com/madou/armory-react/blob/master/src/features/Character/actions.js#L96

 The easiest way to do it I think would be to:
- dispatch `fetchItems` action in `componentWillMount` in https://github.com/madou/armory-react/blob/master/src/features/Guild/components/Logs/index.js#L89 with all item ids found in the logs
- update the selector at https://github.com/madou/armory-react/blob/master/src/features/Guild/components/Logs/index.js#L14 to hook into the items store
- replace any item ids with the name using from state props

:-)
