### ISSUE TITLE
Embedded Tooltips - Incorrect stat names

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#188]
Title says all

**Comment by DomGrieco** [comment]
Ferocity showing as Crit Damage
Expertise showing as Condition Duration
Concentration showing as Boon Duration

**Comment by DxCx** [comment]
Hey,
i've taken a glance look into it, looks like gw2api returns the stats that way, for example:
```
[{attribute: "Power", modifier: 126},
{attribute: "Precision", modifier: 85},
{attribute: "CritDamage", modifier: 85}]
```

however, translation files do know about Ferocity for example,
so we have 2 options:
1. write a mapper for property values
2. fix translations

however, @madou is this change accepted?

**Comment by madou** [comment]
lets fix the translations

**Comment by DxCx** [comment]
i was wrong on my original assumption,
the Attribute translation is not used here, but just lodash's startCase over the attribute.
will be easier to just map.. 💃

**Comment by madou** [comment]
👍
