### ISSUE TITLE
Embedded Tooltips - Ascended trinkets show old exotic gem stats (in grey)

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#189]
![ascended_trinket](https://cloud.githubusercontent.com/assets/6556434/23514020/64acd1c6-ff3c-11e6-93e6-1ac74f12501c.png)

**Comment by DxCx** [comment]
this comes from gw2 api as buff:
```
"infix_upgrade": {
        "id": 599,
        "buff": {
          "skill_id": 15755,
          "description": "+32 Power\n+18 Ferocity\n+18 Precision\n+5 Agony Resistance"
        },
        "attributes": [
          {
            "attribute": "Power",
            "modifier": 126
          },
          {
            "attribute": "Precision",
            "modifier": 85
          },
          {
            "attribute": "CritDamage",
            "modifier": 85
          }
        ]
```

we can eliminate the rendering of that easily, but as i don't have much experience with other items, from reading the API wiki, looks like i can eliminate it for items,
@madou can you confirm that change?

**Comment by madou** [comment]
sure, sounds good. make a update the changelog, update the package.json version (increment patch) and make a pr :)

**Comment by DxCx** [comment]
I'm fixing all blocking issues for @DomGrieco into a branch,
then i'll update changelog with all fixes and such, no worries 👍 

P.S @madou 
why not using [standard-version](https://github.com/conventional-changelog/standard-version)?
or at least just `conventional-changlog`

**Comment by madou** [comment]
cool, sounds great!

no reason for not using standard-version et al really, would be happy to look into using it if it'd streamline things

**Comment by DxCx** [comment]
it basically:
1. builds CHANGELOG out of git commits
2. updates project version by SemVer rules (Breaking Changes / Features / Fixes and misc)
