### ISSUE TITLE
Embedded Tooltips - Elite Specs First Minor Trait

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#193]
The first minor trait on elite specializations shows too much information. For example, Beserker for warrior shows the tooltip for ALL the burst skills. It needs to display "Primal Rage" and nothing more.

**Comment by DxCx** [comment]
https://github.com/madou/armory-react/blob/master/src/common/components/Tooltip/Skill/index.js#L26

this is the reason for all the skills that you are seeing,
however, it looks intentional...
@madou can you shade some light?

**Comment by madou** [comment]
how can we tell what we extra skills we should show (and what we shouldn't)?

**Comment by DxCx** [comment]
That's exactly the point,
it is used to indicate the triat will "open" more skills,
when it's one skill it's really neat, more then one there is much more tooltips then needed,
maybe we should compose to 1 box with icon & name if `skills.length` > 1;

**Comment by DxCx** [comment]
@madou?

**Comment by madou** [comment]
hey, sorry missed this.

when i get home i might just double check what the tooltips look like in game first. still not 100% sure how best to handle this !

**Comment by DxCx** [comment]
Alright, awaiting your response for this one, i would like to include it at the next patchset

**Comment by madou** [comment]
ok so ideally we have something work like ingame (toggle through skills), but how about for now just show the first skill?

**Comment by DomGrieco** [comment]
Or we just show the description and nothing else. That's something gw2efficiency does I believe.

**Comment by madou** [comment]
thats kind boring tho

**Comment by DomGrieco** [comment]
Then I would show just the first skill for now until we come up with another way of implentation.
