### ISSUE TITLE
Embedded Tooltips - Selectable Stats

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#196]
A way to select stats on items that have selectable stats such as legendaries and ascended trinkets.

Found in API: https://api.guildwars2.com/v2/items/77482

`"stat_choices": [
      588,
      656,
      659,
      658,
      660,
      584,
      586,
      583,
      657,
      585,
      592,
      581,
      591
    ]
`

**Comment by DxCx** [comment]
hmm,

i was thinking of allowing encapsulation of both stat selector and id by the '-' symbol
so for this example the data-id will be '77482-656' for eaxmple.
@madou what do you think of that solution?

**Comment by madou** [comment]
hmm

currently in the specialization embed it selects traits like the following:

```
<div
data-armory-ids={id}
data-armory-{id}-traits={traitIds}
>
```

maybe it would be good to do something similar for this. its a little more verbose, but more obvious as to what its doing

so what we could do is:

```
<div
data-armory-ids={id}
data-armory-{id}-stat={statId}
```

we would also need to fetch the selected data, can't remember if I've set up the actions/reducers... will have a look.

**Comment by DxCx** [comment]
alright then i'll keep the existing API competable.. 👍

**Comment by madou** [comment]
it doesnt really look like ive set anything up for item stats atm, lol

in `lib/gw2` theres a method to get the data, though it's pointing to `v2/itemStats` not `v2/itemstats`... might have to change.

have you used redux before? ive made setting up all the gw2 redux logic simple but abstracting it all behind a factory method. if you look in `features/Gw2` folder in any of the reducer files you'll see what I mean. 

create a file called `itemstats.reducer.js`, create the reducer ala: `createReducer('itemstats', readItemStats);`, then export them the same as anything.

you'll then have a new action available if you `import actions from 'features/Gw2/actions', called `itemstats`. so you could just call `actions.fetchItemstats(ids)` in the `<ItemEmbed />` and it'd work exactly as you'd expect.

hopefully i've explained this alright, let me know if you have any questions :)

**Comment by DxCx** [comment]
i am well familar with redux @madou thanks.. :)
but im happy to see how you help people contribute as i am opensource maintainer of a medium-sized project myself.. (https://apollographql.com)

**Comment by DxCx** [comment]
P.S
speaking of redux, you should enable redux dev tools for development builds..
and turn off current logger.. you can search it on youtube for more details

**Comment by madou** [comment]
Will replace it with Dev tools :)

Dude I'm just happy some people are coming to help haha, will help any way I can to accommodate it

**Comment by DxCx** [comment]
hi @madou,
the item_stats api returns different format of attributes, not sure how to convert those,
for example:
https://api.guildwars2.com/v2/itemstats/591
returns:
```json
{
  "id": 591,
  "name": "Berserker's and Valkyrie",
  "attributes": {
    "Power": 0.35,
    "Precision": 0.25,
    "Vitality": 0,
    "CritDamage": 0.25
  }
}
```

so how do i convert those values to stats..?

**Comment by DxCx** [comment]
if you want to see current code, it is here:
https://github.com/DxCx/armory-react/tree/stat-select

**Comment by madou** [comment]
no idea atm man, best bet is to ping the gitter channel for arenanet/api-cdi...

**Comment by DxCx** [comment]
trying my luck there, but in general it looks good, just missing this lookup table and it's done.

**Comment by DxCx** [comment]
Ok so:
https://wiki.guildwars2.com/wiki/Template:Item_stat_lookup
(Actual values are in edit page)

Looks lime abit more work is needed to implement this by construction javascript lookup table
