### ISSUE TITLE
Embedded Tooltips - Grayed out item stats still show on Infusions

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#197]
See picture

![image](https://cloud.githubusercontent.com/assets/6556434/23631991/a45b6686-0296-11e7-98a5-373318a0a96c.png)

**Comment by madou** [comment]
do we know what this _is_ used for? if we just remove this field altogether will things be missing for other items?

**Comment by DomGrieco** [comment]
I'm not entirely sure. It was used in the past for exotic trinkets I think? I'm not sure if it still is.
