### ISSUE TITLE
Embedded Tooltips - Incorrect data in tooltip

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#198]
Tags showing in tooltip here

![image](https://cloud.githubusercontent.com/assets/6556434/23632038/d04fd07e-0296-11e7-90ec-3e782cc13ac6.png)

**Comment by madou** [comment]
This just needs the text passed through the gw2 text parser in `gw2/lib`

**Comment by madou** [comment]
can you give me a specialisation id for this
