### ISSUE TITLE
Embedded Tooltips - Multiple Boon Stats Hard to Read

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#199]
See picture - Stability is hard to read stack count it gives out. 

![image](https://cloud.githubusercontent.com/assets/6556434/23632104/073ef6f0-0297-11e7-8587-e04312f04cff.png)

**Comment by madou** [comment]
can you give me a specialisation id for this for testing?

**Comment by DomGrieco** [comment]
Spec: 27 Trait: 31765
