### ISSUE TITLE
Embedded Tooltips - Damage Values should Round

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#203]
Round damage values, get rid of decimal values.

![image](https://cloud.githubusercontent.com/assets/6556434/23633085/b634ad14-029a-11e7-9c2f-a765e355c9db.png)

**Comment by madou** [comment]
Round up or down?

**Comment by DomGrieco** [comment]
Either round up or split it and round up if decimal is >=5 round down if <5
