### ISSUE TITLE
Setup proper release pipeline

### ISSUE THREAD

**Issue by madou** [madou/armory-react#204]
Currently releases are done like the following:

- Update `CHANGELOG.md`
- Update version in `package.json`
- Check in branch -> deploys automatically to `preview.gw2armory.com
- Check in master -> deploys automatically to `gw2armory.com

Would be good to streamline this (changelog/version updates) and actually tag releases. Open to suggestions !

**Comment by DxCx** [comment]
Standard-version + travis is the solution ive found to be most cost-effective

**Comment by madou** [comment]
already using travis, so thats a bonus !

next step is to setup standard-version i suppose

**Comment by madou** [comment]
we're now deploying to preview with any branch that isnt master, and deploying to production only if master commit is tagged.
