### ISSUE TITLE
Styleable embeds

### ISSUE THREAD

**Issue by Tomelyr** [madou/armory-react#218]
Currently, you are passing an simple `<div>`. If you want to further manipulate this (in my case, i want to have it inline) you can't simply add an rule to your css.

if you give it an class or id it would be much easier to customize it.

https://github.com/madou/armory-react/blob/master/src/embeds/components/Items/index.js#L41
https://github.com/madou/armory-react/blob/master/src/embeds/components/Skills/index.js#L41

**Comment by madou** [comment]
Hey, cool feature!

Classes can definitely be added to make things easier to target. What makes the most sense - each embed gettings a unique class name? E.g: Items -> `gw2a-items-embed` or something?

**Comment by Tomelyr** [comment]
that would be the best way imo, since that way you can decide which one you want to manipulate.
