### ISSUE TITLE
Modify gw2 actions to be a proxy that is debounced so everything is batched together

### ISSUE THREAD

**Issue by madou** [madou/armory-react#225]
Primarily seen as a problem on embeds where if running tons of one skill embeds, there'll be a ton of api calls.

This is undesirable - if we proxy it and batch everything up first we could get some serious perf gains.

**Comment by valento92** [comment]
Just an update: you're correct. The only issue is large number of unique skill embeds, having repeated skills doesn't freeze the page or cause exceptions ([metabattle test](https://metabattle.com/wiki/Template_skill/Ranger)).

**Comment by madou** [comment]
@valento92 what issue was wrong with the page?

**Comment by valento92** [comment]
@madou Wiki has something called #arraymap which iterates over a set of values and outputs something, I came up with a template which guesses what the user wanted to write and suggest some options, but it turned out pretty heavy for every skill and mediawiki was throwing exceptions. I just moved away from that, it shouldn't be that difficult to refer to a skill index page to find possible options.

**Comment by madou** [comment]
ah ok cool. whats the current progress of figuring out what needs to be done before using gw2a embeds in prod?

**Comment by valento92** [comment]
I'll just manually find all skill/trait ids. Once I have all of those I'll validate our template and see if wiki responds well to the change.

**Comment by madou** [comment]
@valento92 hey theres a new build up on preview.gw2armory.com

it has the batching logic, have a play if u want!

**Comment by valento92** [comment]
It works quite nicely on my smart phone. The only time it slowed down was when I opened the page from GMail, but the embed GMail mobile's browser thing (or Facebook's, for that matter) are complete trash so I don't count those. Opening in Chrome, either desktop or mobile worked pretty nice.

Thy magic works, man!

**Comment by madou** [comment]
@valento92 how much did it slow down in gmail/facebook embed browser?

**Comment by valento92** [comment]
Not much, but maybe my Galaxy S4 is a bit outdated (2013).
