### ISSUE TITLE
Add ability to have "question mark boxes" for skills/items

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#229]
It would be nice if we had, for skills and trait, a way to identify such slot as "optional". Say we have these three builds and the utils are fixed, except for a slot which can take up on a few choices, so it would be cool if we had "gw2armory-skill-optional" which would skip API pull and just produce an empty dark square with a question mark, as in "this is optional". Then, obviously one would state in their guide which skills would fill that slot.

Same for traits, but not sure how that would work. Maybe if we had a "0" parameter in which a certain column wouldn't have any traits highlighted?

**Comment by madou** [comment]
Cool idea!

For skills/equips I'm thinking something like a question mark to signify make it an empty box.

So, if we think about how the current embed markup looks like, just add a `?` instead of an id.

```
<div
  data-armory-embed="skills"
  data-armory-ids="5507,?,5510"
>
</div>
```

For traits, you don't have to highlight anything! So if we have two specs (id#1, id#16), just don't add traits to be highlighted for one of them!

```
<div
  data-armory-embed="specializations"
  data-armory-ids="1,16"
  data-armory-1-traits="700,1960,1950"
>
</div>
```

Note that id#16 doesn't have a `data-armory-1-traits` attribute, so it won't have anything highlighted!

**Comment by valento92** [comment]
I mean, a certain _column_ without highlight, not the entire specialization tree.

**Comment by madou** [comment]
That's still possible ATM, just don't pass in the Id of the trait :) you
can pass more or less trait ids than 3!

**Comment by valento92** [comment]
Ah, cool! Will try that out, thanks.

**Comment by madou** [comment]
@valento92 do you have a good image/icon I can use for the question mark box? gw2 asset please... !

**Comment by valento92** [comment]
@madou I'll see what I can find.

**Comment by valento92** [comment]
These are what I found from a quick look at 128x128, 64x64 and 32x32 folders.

![102424 x64](https://cloud.githubusercontent.com/assets/6351070/23947473/4b67f614-0955-11e7-81ad-c3e7ad893cc9.png)
![156021 x128](https://cloud.githubusercontent.com/assets/6351070/23947474/4b6a3a64-0955-11e7-9b33-cf5f839f11ff.png)

**Comment by madou** [comment]
second image could potentially work. do you have a empty bag slot icon on hand too?

**Comment by valento92** [comment]
Okay, here goes a handful of images which hopefully will help you!
![156020 x128](https://cloud.githubusercontent.com/assets/6351070/23951218/e98cc294-0963-11e7-8c40-a6e2823a1514.png)
![156021 x128](https://cloud.githubusercontent.com/assets/6351070/23951214/e9830218-0963-11e7-9810-b36f437783f8.png)
![156022 x128](https://cloud.githubusercontent.com/assets/6351070/23951215/e9834598-0963-11e7-9a83-692087074ec6.png)
![156032 x128](https://cloud.githubusercontent.com/assets/6351070/23951216/e984e024-0963-11e7-8124-3ffc4e9afe02.png)
![603449 x128](https://cloud.githubusercontent.com/assets/6351070/23951217/e985499c-0963-11e7-87bb-cfee1aec87be.png)
![156670 x32](https://cloud.githubusercontent.com/assets/6351070/23951228/ef5ed31a-0963-11e7-8a9f-1cdefd272fc1.png)
![156671 x32](https://cloud.githubusercontent.com/assets/6351070/23951227/ef5e7da2-0963-11e7-9d39-528ce2f80dab.png)
![157098 x32](https://cloud.githubusercontent.com/assets/6351070/23951232/ef658278-0963-11e7-8ece-8332cf1e1e0f.png)
![157099 x32](https://cloud.githubusercontent.com/assets/6351070/23951231/ef648e68-0963-11e7-8b0a-d47b3899d625.png)
![358368 x32](https://cloud.githubusercontent.com/assets/6351070/23951229/ef61ba94-0963-11e7-9811-2e43842567c1.png)
![358370 x32](https://cloud.githubusercontent.com/assets/6351070/23951235/ef832e0e-0963-11e7-8b53-ffd365561f93.png)
![733359 x64](https://cloud.githubusercontent.com/assets/6351070/23951233/ef7db618-0963-11e7-88e2-d2a0ce5b745a.png)
![866125 x64](https://cloud.githubusercontent.com/assets/6351070/23951234/ef813ac2-0963-11e7-98e3-fc7aee8f1565.png)
![1002138 x64](https://cloud.githubusercontent.com/assets/6351070/23951236/ef86f0de-0963-11e7-90e9-c883d6fa2456.png)

And, if I'm not wrong, these next assets are used for "optional skill slot":
![440031 x64](https://cloud.githubusercontent.com/assets/6351070/23951265/0289d02a-0964-11e7-8e61-611087e6fb0d.png)
![440032 x64](https://cloud.githubusercontent.com/assets/6351070/23951266/028a1616-0964-11e7-9dcb-1238c7ef4c62.png)
![440033 x64](https://cloud.githubusercontent.com/assets/6351070/23951264/0288838c-0964-11e7-9135-109679ddcd82.png)

**Comment by madou** [comment]
@valento92 cool, thanks man.

**Comment by valento92** [comment]
Bumps! :D

**Comment by madou** [comment]
@valento92 hey! this will be in soon. the first step of this has already been done (see: your comment in gitter about the border :P)

im just on holiday for a few days, cant do much! (feel free to make a PR tho if you want it faster lol!)

**Comment by valento92** [comment]
I'm not quite proficient with front-end, and sorry... just a bit anxious 'bout this one. I'll wait for ya! :)

**Comment by madou** [comment]
@valento92 I'm thinking about allowing custom text for ? Items, but what do you think a sane default should be? "Optional x"? Where x is item, skill, etc.

**Comment by madou** [comment]
And why are you anxious :P

**Comment by valento92** [comment]
I think "Optional" suffices, what do you think? Anxiety is something I have to endure on a daily basis, don't mind it! hahaha

**Comment by madou** [comment]
Ok ;-)

**Comment by madou** [comment]
@valento92 hey, see https://preview.gw2armory.com/embeds/example/index.html for a preview of this.

just need to add some unit tests before deploying (and maybe adjust the background so its css and not an image)

release in a few days

**Comment by valento92** [comment]
Oh, this looks really good! Great job, my friend. :grin:

**Comment by madou** [comment]
@valento92 deploying to production !

**Comment by valento92** [comment]
Yay, thank you. :grin:
