### ISSUE TITLE
Closing tag bug

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#247]
About latest commit:
gw2armory.com/0-chunk-83d7cee5.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by valento92** [comment]
Oh nvm, somehow I needed to clear localstorage for things to work correctly. Heh

**Comment by madou** [comment]
Actually it was from a bad env variable set during the deployment and it
build the webpack publicPath as preview instead of prod.. but ah yeah!
sorry!

**Comment by valento92** [comment]
@madou yeah, I felt like something was odd but didn't want to pester you. :tongue:
