### ISSUE TITLE
Add ability to control embed slot size

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#248]
Something like "size"? You currently fix the size to 60x60, but it's very handy if you could change it. In my opinion it doesn't have to set each skill slot size to a different one, but the full row, as it seems a bit awkward to have a mix of differently-sized slots in the same container.

It's minor, not sure how difficult it is to create this.

Thanks again. =)

**Comment by madou** [comment]
@valento92 you can always modify the size with css for now? :)

**Comment by valento92** [comment]
@madou Possibly, I'll do this thing inline LOL... not a big deal, template is something reusable in the wiki so I can change later hahah

**Comment by madou** [comment]
dont think inline styles will work for this
