### ISSUE TITLE
New batching can eventually hit api limits of total amount of items allowed to request at one time

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#251]
I'm mapping trait numbers with my new [specialization template](https://metabattle.com/wiki/Template:ESpecialization), but it's no longer showing them... it was fine before last patch. Something suspicious is output to the console.

![issue](https://cloud.githubusercontent.com/assets/6351070/24505956/e323a978-1529-11e7-9806-fd01dd1a33fb.png)

**Comment by valento92** [comment]
Well, there are two things:
* Trying the script with jsfiddle works normally.
* Opening the same page with Firefox works normally.

Also, there's seems to be an ongoing issue with Chrome the way [files are saved](http://stackoverflow.com/questions/36133715/google-chrome-failed-parsing-sourcemap-css-map-web-essential).

**Comment by valento92** [comment]
Never mind, same thing as the other day: cleared localstorage and it's okay now!!!

**Comment by valento92** [comment]
No, there's something really odd. I don't know why, but it seems that after the initial load, the subsequent ones don't work fine for traits. For example, I cleared my localstorage and then entered a page that uses a few specializations, it showed all of those which had traits specified. Then, I tried to preview one specialization that I haven't previously loaded the first time (by specifying its traits) and they don't show up.

It seems to me that the script works fine the first time it loads data, on the next ones with some data already in place it doesn't work fine. Or I'm doing something super silly. :(

**Comment by valento92** [comment]
And it only affects traits by now.

**Comment by valento92** [comment]
Well, ahm, it seems I was trying to get too many specializations onscreen because I was just testing some stuff, and it caused your script to fire a request asking for a lot of traits at once. I'm... ahm... sorry.

![uh](https://cloud.githubusercontent.com/assets/6351070/24524217/c57c5a5c-1563-11e7-8637-4a30b38c864c.png)

**Comment by madou** [comment]
Ah that's an interesting point though! Because it batches everything now depending how many things you've placed you might hit api limits (amount you're allowed to get back at one time).

**Comment by valento92** [comment]
@madou Yeah, for a small amount I breached their limit, since: 9 classes * 6 specs/ea * 12 traits/ea = 648.

However I think the limit is per request, not ids, isn't it? Of course it doesn't justify because it's rather weird to have those many ids there, but yeah...

**Comment by madou** [comment]
Yeah it's per request, you're only allowed to request a finite amount of objects in one request!

The source map thing is weird, but not a big deal atm.

P.S: Don't rely on clearing local storage for fixing things! If it doesn't work out of the box something wrong - the users using the embeds won't be clearing theirs probably ;)

**Comment by madou** [comment]
@valento92 yo i've added a fix for this

its deploying to preview atm, when it gets there can you try it out?

https://travis-ci.org/madou/armory-react/builds/216957401

**Comment by valento92** [comment]
Worked beautifully, you're awesome.
