### ISSUE TITLE
Create trait embed

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#253]
Just like skills. Right now we can only display a full spec tree, but it would be quite nice if we had traits alone to be used inline within the text (eg. guide). Style would be roughly the same as skills.

**Comment by madou** [comment]
Ah, yeah ok

**Comment by valento92** [comment]
And sorry for not so descriptive titles!

**Comment by madou** [comment]
lol you're fine dw

**Comment by madou** [comment]
@valento92 whats SMW
