### ISSUE TITLE
Allow items embed to select skins

### ISSUE THREAD

**Issue by madou** [madou/armory-react#296]

**Comment by stygiansabyss** [comment]
Any word on if this will become a thing.  I had figured that something like `data-armory-<id>-skin=<skin id>` would have worked.

**Comment by madou** [comment]
hey @stygiansabyss 

it can be, im just not actively working on the armory atm (other than modifying it to be on brand for path of fire)

would you be keen to implement this?

**Comment by stygiansabyss** [comment]
If I knew how. I am competent with js but I mainly work in php.

**Comment by madou** [comment]
@stygiansabyss 

tooltip components here: https://github.com/madou/armory-react/tree/master/src/common/components/Tooltip

embeds here: https://github.com/madou/armory-react/tree/master/src/embeds

i can answer any questions you have

**Comment by stygiansabyss** [comment]
It looks like the component has the ability to use a skin.  Currently trying to understand how this gets called.  I am assuming somewhere looks for data-armory-embed and uses that to determine which modules to load.  At which point it loads the creator file and passes that data to the component file?

**Comment by madou** [comment]
The embed?

From start to finish (links go to lines of code):

1. User adds the `gw2aEmbeds.js` script to their page
2. `DOMContentLoaded` event is triggered
3. [This line of code](https://github.com/madou/armory-react/blob/master/src/embeds/bootstrap.js#L55) is eventually fired, which collects all elements on the page that have a `data-armory-embed` attribute. The value of this attribute is the embed name.
4. The embed is [imported asynchronously here](https://github.com/madou/armory-react/blob/master/src/embeds/bootstrap.js#L65) and then is instantiated and passed props
5. Let's say we're loading the items embed. [This creator is then called](https://github.com/madou/armory-react/blob/master/src/embeds/creators/items.js), does any calculations it needs to get extra data from the div, and then returns the `<Items />` embed component.
6. [That being this component](https://github.com/madou/armory-react/blob/master/src/embeds/components/Items/index.js)

For tooltip, there are two main things:

1. The [`TooltipTrigger`](https://github.com/madou/armory-react/blob/master/src/common/components/TooltipTrigger/index.js)
2. And the [`Tooltip`](https://github.com/madou/armory-react/blob/master/src/common/components/Tooltip/index.js#L62) itself

You won't have to worry about modifying the `TooltipTrigger` for this feature, but you _will_ have to add a new case in the `Tooltip` switch to handle skins, as well as creating a new component for the skin content. [Look at the `Item` tooltip for inspiration!](https://github.com/madou/armory-react/blob/master/src/common/components/Tooltip/Item/index.js)

Hope this helps

**Comment by stygiansabyss** [comment]
Thanks. I've started on it but had to stop for work. Will keep going asap

**Comment by stygiansabyss** [comment]
Thank you for that.  It looks like I will need to add something like character actions has inside fetchCharacter that grabs the skins and then the character component seems to add it to the skins array which is then passed to the tool tip.  Just need to figure out how to get the skin from the item component.

**Comment by madou** [comment]
Is this just for a skins embed?

If it is, don't worry about `fetchCharacter`. 

What you want to do is create a `skins creator`, use this items creator for inspiration: https://github.com/madou/armory-react/blob/master/src/embeds/creators/items.js

Then create a `Skins` embed component, use `Amulets` https://github.com/madou/armory-react/blob/master/src/embeds/components/Amulets/index.js for inspiration.

There is already a `Skin` component ready for you to use: https://github.com/madou/armory-react/blob/master/src/common/components/Gw2Skin/index.js

Just use that component, and pass it the ids you want. The data will be fetched in the background. What's missing is the `Skin` tooltip! So make that!

**Comment by stygiansabyss** [comment]
Ok, so my goal was to supplement the items embed to allow for skins.  So we would do `data-armory-{ITEM_ID}-skin="{SKIN_ID}`.  Then it would use the icon of the skin with the details of the item itself.  Similar to how the full character one does it.

**Comment by madou** [comment]
oh! i misunderstood then, sorry :)

🤔 you'd have to bring in the action for fetching skins, pass them the ids from the embed, modify the selector in the items embed to bring the skins, and then pass the skin data down into the `Items` component

**Comment by stygiansabyss** [comment]
I dont see a fetching Skins action.  It looks like character/actions.js is just calling a magic method of some kind on gw2/actions.js.

(sorry for the delay, had work stuff to get pushed crazy fast)

**Comment by madou** [comment]
Yeah the GW2 actions are made in a little bit of a magical way. If you're
interested look in features/GW2/reducerFactory.

Just assume if you use the skins action like you've seen it will work
otherwise


On 8 Aug. 2017 7:30 am, "Travis Blasingame" <notifications@github.com>
wrote:

I dont see a fetching Skins action. It looks like character/actions.js is
just calling a magic method of some kind on gw2/actions.js.

(sorry for the delay, had work stuff to get pushed crazy fast)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/madou/armory-react/issues/296#issuecomment-320786157>,
or mute the thread

**Comment by stygiansabyss** [comment]
I know this isnt correct, but heres where I am so far.

https://github.com/stygiansabyss/armory-react/commit/9506b7e882c0eb96bae03d0157ec360cb88c82a7

error in browser is `Warning: `NaN` is an invalid value for the `width` css style property. Check the render method of `Icon`.` and the skin is still not being used.  But if I log the skin in item index it does get a valid skin object.

**Comment by madou** [comment]
ill have a look when i get a chance

**Comment by madou** [comment]
dw about the error in the browser, thats an existing thing

**Comment by madou** [comment]
@stygiansabyss hey mate, sorry I haven't been that helpful.

i ended up implementing this for you, check out the pull request: https://github.com/madou/armory-react/pull/344

just need to fix the build and add some unit tests.

check it out ! :)

**Comment by madou** [comment]
merged.
