### ISSUE TITLE
Character Embed doesnt link to Gw2armory

### ISSUE THREAD

**Issue by Tomelyr** [madou/armory-react#306]
Hey,

if you include the character sheet into your own site, the link for the profile isn't working, since you aren't setting the link to gw2armory.

https://github.com/madou/armory-react/blob/master/src/embeds/components/Character/index.js#L89

so if you want to click on the name, it will redirect you to yoursite.com/c/Char Name instead of gw2armory.com/c/Char Name, which won't work ofc, since yoursite isnt gw2armory :)

Greetings

**Comment by madou** [comment]
oh nice find, i'll fix it up

thanks!

**Comment by Tomelyr** [comment]
on the wvw community of Abaddons Mouth [DE] :)

**Comment by madou** [comment]
@Tomelyr hi this is now fixed.

send me a link when you have the embeds! would like to see :angel:

**Comment by Tomelyr** [comment]
Sorry, but currently it is only used in the non public area of the forum, since i've included it as an BBCode-
The forum itself can be found under https://abaddons-maul.de/ 

except this one post, since i've included it into my signature there :) 
https://abaddons-maul.de/thread/956-verifizierung-im-forum/?postID=19029#post19029

**Comment by madou** [comment]
cool! no worries - still awesome to see the embeds being used :)

if you have any feature requests let me know!

as a side do you know about the authenticated guild features of gw2armory? trying to get it more exposure : P
