### ISSUE TITLE
Provide an option to display an inline link beside an embed icon

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#328]
Following [this usage](https://metabattle.com/wiki/Build:Chronomancer_-_Chronophantasma_Shatter#Slot_Changes), the idea would be to replicate this behavior in a broader sense but allowing a little flexibility.

Name it, maybe, data-armory-link. It could contain a wildcard "*" in order to just write down a certain skill's/item's/trait's/etc canonical name, or an url that would link somewhere. In this case you could have like:

`if data-armory-link == *`
`    (subject name)`
`else`
`    <a href="${data-armory-link}">(subject name)</a>`

Either an url or just the name, but both always displaying the name. It would be helpful because we can't control (at least not easily I think) which components does the mouse-over tooltip listens to. And since we're looking at usability, it would be very important when reading written guides because this kind of presentation feels more natural to read.

The way metabattle is doing it now is showing your icon but it feels disconnected to have only the icon display the tooltip.

**Comment by madou** [comment]
good feature request, i'll look into it soon
