### ISSUE TITLE
Possible bug: repeating food names at details section

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#329]
Per this image:
![repeating](https://user-images.githubusercontent.com/6351070/29212174-17d1ce20-7e6b-11e7-8625-6663867f6242.png)

When "type" is "Consumable" and details.type is "Food" the name is repeating. It's not a biiiig deal and it doesn't hurt visibility at all, just thought to point it out.

You know... foods have smaller tooltips so these things always catch your eyes. haha

@Edit
API key: https://api.guildwars2.com/v2/items?ids=12464&lang=en

**Comment by madou** [comment]
nice catch
