### ISSUE TITLE
Color skill types in embeds

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#343]
When viewed in-game, a certain skill type is colored the same way as skill name. Right now they don't offer a way for us to know that info from the API. I [opened an issue](https://github.com/arenanet/api-cdi/issues/562) for them to make it error-free to catch that info; for now all we have is a subject-to-change list of skill types:

`Cantrip | Deception | Glyph | Mantra | Meditation | Physical | Shout | Signet | Stance | Trap | Well | Consecration | Final Charge | Spirit weapon | Symbol | Tome | Virtue | Ward | Citadel Order | Legendary Assassin | Legendary Centaur | Legendary Demon | Legendary Dragon | Legendary Dwarf | Legendary Renegade | Banner | Burst | Primal burst | Rage | Engineering kit | Elixir | Exceed | Gadget | Gyro | Photon Forge | Tool belt | Turret | Celestial Avatar | Pet | Spirit | Survival | Dual Wield | Kneel | Stealth Attack | Stolen skill | Trick | Venom | Arcane | Attunement | Conjure | Dual Attack | Overload | Ambush | Clone | Glamour | Manipulation | Phantasm | Shatter | Corruption | Mark | Minion | Punishment | Shade | Spectral `

And I'm surprised they renamed kits to "Engineering kits" (been away from the game for a couple months now). lol

**Comment by madou** [comment]
Can you show image example

**Comment by valento92** [comment]
Yep:
![skilltypeexample](https://user-images.githubusercontent.com/6351070/30244585-e9f14982-958e-11e7-95c7-8d32fd2cd83e.jpg)

**Comment by madou** [comment]
This is now released.
