### ISSUE TITLE
Optional embed images are semi-opaque

### ISSUE THREAD

**Issue by valento92** [madou/armory-react#346]
There's a rule in `g1OOz` class that sets the corresponding div opacity to 0.7; this transparency doesn't look good when the div is on top of other visible elements. Image below shows an [example](https://metabattle.com/wiki/User:LordShuckle/SkillbarProject/Template).

![opacity](https://user-images.githubusercontent.com/6351070/30530036-2cbe2018-9c11-11e7-8646-de4c6090f80f.png)

**Comment by madou** [comment]
fixed.
