### ISSUE TITLE
Some mistakes in zh.json

### ISSUE THREAD

**Issue by danroger** [madou/armory-react#351]
There are some translation errors in Chinese.
Base on the Chinese client,it should be more accurate at the flow:
-"transmuted": "幻化",
-"skinLocked": "皮肤锁定",
-"weaponStrength": "武器威力",
-"defense": "防御力",
-"power": "威力",
-"toughness": "坚韧",
-"boonDuration": "增益持续时间",
-"conditionDuration": "症状持续时间",
-"expertise": "症状效果",
-"concentration": "增益效果",
-"elementalist": "协调冷却率",
-"mesmer": "粉碎技能冷却率",
-"herald": "预告者",
-"soulbeast": "魂兽师",
-"weaver": "编织者",
-"holosmith": "全息师",
-"deadeye": "神枪手",
-"mirage": "幻象师",
-"scourge": "灾厄师",
-"spellbreaker": "破法者",
-"firebrand": "燃火者",
-"renegade": "龙魂使"

An editor from mists.co

**Comment by madou** [comment]
hi @danroger, thanks! would you like to submit a pull request?

**Comment by danroger** [comment]
Actually, I dont know how to use github at all, so I dont know how to upload my path. @

**Comment by madou** [comment]
no worries then, will patch it up for you.
