### ISSUE TITLE
Generic "componetised" embed

### ISSUE THREAD

**Issue by madou** [madou/armory-react#89]
Idea is to have one embed that is built up of other components.

User chooses the size, background, (basic structure) of the embed, then can drag components on.

Examples of components being:
- Character name/skills/traits/etc
- Character portrait
- ??
- Profit

The dream would mean that instead of creating one off embeds that are static - this would allow of infinite combinations and would suite everyones needs.

E.g: http://imgur.com/a/dk2bH

**Comment by iraking** [comment]
http://imgur.com/a/dk2bH
